name: CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        npm install
        cd client
        npm install

    - name: Lint server
      run: npm run lint
      
    - name: Lint frontend
      run: | 
        cd client
        npm run lint

    - name: Run frontend tests
      run: |
        cd client
        npm run test

    - name: Build
      run: npm run build
